### ISSUE TITLE
`operate!!` not defined error (from JuMP.jl)

### ISSUE THREAD

**Issue by JinraeKim** [jump-dev/MutableArithmetics.jl#128] opened 2021-12-08 08:41 UTC
After some inspection, I found that [MutableArithmetics.jl](https://github.com/jump-dev/MutableArithmetics.jl/blob/master/src/rewrite.jl) does not properly have the function `operate!!`.

```julia
(@v1.7) pkg> add MutableArithmetics
    Updating registry at `~/.julia/registries/General.toml`
   Resolving package versions...
    Updating `~/.julia/environments/v1.7/Project.toml`
  [d8a4904e] + MutableArithmetics v0.3.1
  No Changes to `~/.julia/environments/v1.7/Manifest.toml`

julia> using MutableArithmetics

julia> const _MA = MutableArithmetics
MutableArithmetics

julia> _MA.operate!!
ERROR: UndefVarError: operate!! not defined
Stacktrace:
 [1] getproperty(x::Module, f::Symbol)
   @ Base ./Base.jl:35
 [2] top-level scope
   @ REPL[5]:1
```

_Originally posted by @JinraeKim in https://github.com/jump-dev/JuMP.jl/issues/2821#issuecomment-988607732_

**Comment by odow** [comment] 2021-12-08 18:33
Version 0.3.1 certainly does have `operate!!`:
https://github.com/jump-dev/MutableArithmetics.jl/blob/c4c2e7ac3f3b709c0f25074dd206fdcf5dc7e3b5/src/interface.jl#L423-L430

What happens if you add MutableArithmetics in a new environment?

What is your JuMP environment with `] st -m`?

**Comment by odow** [comment] 2021-12-08 18:52
For example, I cannot reproduce this:
```Julia
(base) oscar@Oscars-MBP /tmp % ~/julia-1.7 --project=ma
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.7.0 (2021-11-30)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

(ma) pkg> st
      Status `/private/tmp/ma/Project.toml` (empty project)

(ma) pkg> add MutableArithmetics
    Updating registry at `~/.julia/registries/General`
    Updating git-repo `https://github.com/JuliaRegistries/General.git`
   Resolving package versions...
    Updating `/private/tmp/ma/Project.toml`
  [d8a4904e] + MutableArithmetics v0.3.1
    Updating `/private/tmp/ma/Manifest.toml`
  [d8a4904e] + MutableArithmetics v0.3.1
  [56f22d72] + Artifacts
  [2a0f44e3] + Base64
  [b77e0a4c] + InteractiveUtils
  [8f399da3] + Libdl
  [37e2e46d] + LinearAlgebra
  [56ddb016] + Logging
  [d6f4376e] + Markdown
  [9a3f8284] + Random
  [ea8e919c] + SHA
  [9e88b42a] + Serialization
  [2f01184e] + SparseArrays
  [8dfed614] + Test
  [e66e0078] + CompilerSupportLibraries_jll
  [4536629a] + OpenBLAS_jll
  [8e850b90] + libblastrampoline_jll

julia> using MutableArithmetics

julia> const _MA = MutableArithmetics
MutableArithmetics

julia> _MA.operate!!
operate!! (generic function with 2 methods)
```

**Comment by odow** [comment] 2021-12-09 01:22
Are you sure you can reproduce this?

```Julia
(base) oscar@Oscars-MBP Desktop % ~/julia-1.7
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.7.0 (2021-11-30)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

(@v1.7) pkg> st
      Status `~/.julia/environments/v1.7/Project.toml`
  [6e4b80f9] BenchmarkTools v1.2.1
  [c3a54625] JET v0.5.2 `https://github.com/aviatesk/JET.jl.git#master`
  [295af30f] Revise v3.1.20
  [aa65fe97] SnoopCompile v2.8.0
  [e2b509da] SnoopCompileCore v2.8.0

(@v1.7) pkg> add JuMP
    Updating registry at `~/.julia/registries/General`
    Updating git-repo `https://github.com/JuliaRegistries/General.git`
   Resolving package versions...
    Updating `~/.julia/environments/v1.7/Project.toml`
  [4076af6c] + JuMP v0.22.1
    Updating `~/.julia/environments/v1.7/Manifest.toml`
  [49dc2e85] + Calculus v0.5.1
  [d360d2e6] + ChainRulesCore v1.11.2
  [9e997f8a] + ChangesOfVariables v0.1.1
  [523fee87] + CodecBzip2 v0.7.2
  [944b1d66] + CodecZlib v0.7.0
  [bbf7d656] + CommonSubexpressions v0.3.0
  [34da2185] + Compat v3.40.0
  [864edb3b] + DataStructures v0.18.11
  [163ba53b] + DiffResults v1.0.3
  [b552c78f] + DiffRules v1.5.0
  [ffbed154] + DocStringExtensions v0.8.6
  [f6369f11] + ForwardDiff v0.10.23
  [3587e190] + InverseFunctions v0.1.2
  [92d709cd] + IrrationalConstants v0.1.1
  [4076af6c] + JuMP v0.22.1
  [2ab3a3ac] + LogExpFunctions v0.3.5
  [b8f27783] + MathOptInterface v0.10.6
  [d8a4904e] + MutableArithmetics v0.3.1
  [77ba4419] + NaNMath v0.3.5
  [276daf66] + SpecialFunctions v1.8.1
  [90137ffa] + StaticArrays v1.2.13
  [3bb67fe8] + TranscodingStreams v0.9.6
  [6e34b625] + Bzip2_jll v1.0.8+0
  [efe28fd5] + OpenSpecFun_jll v0.5.5+0
  [8bb1440f] + DelimitedFiles
  [1a1011a3] + SharedArrays
  [05823500] + OpenLibm_jll

julia> exit()
(base) oscar@Oscars-MBP Desktop % ~/julia-1.7 --project=jump-bug
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.7.0 (2021-11-30)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

(jump-bug) pkg> st
      Status `~/Desktop/jump-bug/Project.toml` (empty project)

julia> using JuMP
[ Info: Precompiling JuMP [4076af6c-e467-56ae-b986-b466b2749572]

julia> JuMP._MA
MutableArithmetics

julia> JuMP._MA.operate!!
operate!! (generic function with 4 methods)
```

If so, what is `VERSION` and `versioninfo()`, as well as `] st -m`.

**Comment by odow** [comment] 2021-12-09 01:40
I assume you updated your packages without restarting Julia. 

If run `using Foo` and then `] up Foo`, the old version of `Foo` is used until you restart Julia, even though `] st` will show the new version.

I'll close this, but feel free to re-open if you can reproduce this in future.

**Closed by odow** 2021-12-09 01:40 UTC
