### ISSUE TITLE
dot with two Hermitian matrices

### ISSUE THREAD

**Issue by blegat** [jump-dev/MutableArithmetics.jl#203] opened 2023-02-27 09:57 UTC
As notice in https://github.com/jump-dev/JuMP.jl/issues/3242#issuecomment-1445497276, `dot(::Hermitian, ::Hermitian)` does not get redirected in `dispatch.jl`. This means the slow `LinearAlgebra` implementation will get used and allocate a lot of intermediate JuMP expressions.

**Comment by odow** [comment] 2023-11-30 00:16
Closing as duplicate of #234

**Closed by odow** 2023-11-30 00:16 UTC
Labels: Type: Performance
